os: osx
osx_image: xcode10.2
install:
  - pipenv --three install --deploy --dev
addons:
  homebrew:
    packages:
    - pipenv
    - shellcheck
    update: true
before_script: shellcheck mac -e SC2039
script: sh mac
after_success: pipenv run mkdocs build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: site
  on:
    branch: master