os: osx
osx_image: xcode10.2
install:
  - pipenv --three install --deploy --dev
addons:
  homebrew:
    packages:
    - pipenv
    - shellcheck
    update: false
jobs:
  include:
    - stage: lint
      script: shellcheck mac -e SC2039
    - stage: mac
      script: sh mac
    - stage: docs
      script: pipenv run mkdocs build
